apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
spec:
  strategy: allInOne
  allInOne:
    options:
      query:
        base-path: "/jaeger"
  ingress:
    enabled: true
    pathType: Prefix
    hosts:
      - localhost
